### ISSUE TITLE
Continuous disconnections to the MQTT broker

### ISSUE THREAD

**Issue by Simoverdex** [cmcgerty/Sofar2mqtt#15]
Hi, I recently made the sofar2mqt project. It works great except that sporadically the device disconnects to the mosquet broker, and I am forced to remove and restore power to the device to reconnect the broker. I have increased the Keepalive value in the mosquet configuration, but the situation does not change. Does anyone have any suggestions about it?

I Have Home Assistant OS 2021.12.10 on Raspberry PI 4

This is the Mosquitto Log
![IMG_0098](https://user-images.githubusercontent.com/59848230/150603121-840f494f-c365-40a0-8d79-e130c82334f8.jpeg)

**Comment by cmcgerty** [comment]
Hi @Simoverdex .

Sofar2mqtt V2.0 beta1 has been published today, which is a major write and should bring much greater stability. See if that is better for you.
