### ISSUE TITLE
readme should say subscribe Sofar2mqtt/state - capital S

### ISSUE THREAD

**Issue by rustle118** [cmcgerty/Sofar2mqtt#17]

**Comment by rustle118** [comment]
Sofar2mqtt/state currently readme has lower case s for sofar

**Comment by cmcgerty** [comment]
Quite so. My bad. The mqtt message root is actually whatever you call the device in the line deviceName = "Sofar2mqtt";

Thanks,
Colin
________________________________

**Comment by cmcgerty** [comment]
V2.0 beta1 has been published today, which is a major write and bring much greater stability. See if that is better for you.
