### ISSUE TITLE
upgraded to 2.0b1 but still CRC errors

### ISSUE THREAD

**Issue by javiermitchell** [cmcgerty/Sofar2mqtt#29]
I have upgraded to 2.0b1 and found it more stable - I think -
However, when I thought everything was sorted I'm getting one of those dreaded "CRC-FAULT"errors 
So things are still not completely fixed, by the looks of it.
The annoying thing is there doesn't seem to be quick solution: you just leave it as it is and it will sort itself after it restarts the next day

In any case, I think this is a good effort

**Comment by double1968** [comment]
since I have been using this adapter instead of the blue one I have not had any problems for now.
I'm on 2.0b1 too.
Also on github they recommend it

[https://www.amazon.it/gp/product/B096ZXXKCR/ref=ppx_od_dt_b_asin_image_s00?ie=UTF8&psc=1](url)

**Comment by javiermitchell** [comment]
what do you mean?
this ONE is BLUE!

**Comment by double1968** [comment]
[https://github.com/cmcgerty/Sofar2mqtt](url)

section How To Build

![image](https://user-images.githubusercontent.com/48420012/193101907-db67cb77-0e9c-40f2-a803-c9b75f71f242.png)

**Comment by javiermitchell** [comment]
sorry, I misunderstood: you MEANT the blue BOARD, I thought you meant the blue CONNECTOR
so should be the red BOARD
Thanks

**Comment by frogsuk** [comment]
> since using this adapter instead of the blue one I have had no more problems.
> 
> I'm on 2.0b1 too.
> 
> Also on github they recommend it
> 
> 
> 
> `https://www.amazon.it/gp/product/B096ZXXKCR/ref=ppx_od_dt_b_asin_image_s00?ie=UTF8&psc=1`

This is not the MAX3485 Chipped board as quoted in GitHub. It is the MAX13487E board and there is a difference.
Please see attached data sheets.
Always check the main chip in the board for it's number as not always described correctly

https://datasheets.maximintegrated.com/en/ds/MAX13487E-MAX13488E.pdf

https://datasheets.maximintegrated.com/en/ds/MAX3483E-MAX3491E.pdf
